import { useEffect, useState } from "react";
import Head from "next/head";
import Navbar from "../components/organisms/navbar";
import { Breadcrumb, Col, Row } from "react-bootstrap";
import { BiSave } from "react-icons/bi";
import axios from "axios";
import Link from "next/link";
import { useRouter } from "next/router";
import Swal from "sweetalert2";

function TambahJenis() {
  const router = useRouter();
  const [nama, setNama] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = () => {
    setIsLoading(true);
    axios
      .post("/api/simpanBarang", { nama_barang: nama, stok, jenis })
      .then((res) => {
        Swal.fire({
          icon: "success",
          title: "Succseed",
          text: "Berhasil Tambah barang",
        })
          .then((result) => (result.isConfirmed ? router.replace("/") : null));
      })
      .catch((err) => {
        console.log(err);
        setIsLoading(false);
        Swal.fire({
          icon: "error",
          title: "Oops...",
          text: err?.response?.data?.message,
        });
      })
      .finally(() => {
        setIsLoading(false);
      });
  };

  return (
    <>
      <Head>
        <title>Tambah Jenis Barang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container mt-4">
        <Breadcrumb>
          <Link href="/" passHref>
            <Breadcrumb.Item>Home</Breadcrumb.Item>
          </Link>
          <Breadcrumb.Item active>Tambah Jenis Barang</Breadcrumb.Item>
        </Breadcrumb>
        <Row>
          <Col md={{ span: 6, offset: 3 }}>
            <form
              onSubmit={(e) => {
                e.preventDefault();
                handleSubmit();
              }}
            >
              <div className="mb-3">
                <label for="namaJenisBarang" className="form-label">
                  Nama Jenis
                </label>
                <input
                  type="text"
                  className="form-control"
                  id="namaJenisBarang"
                  placeholder="Nama Jenis"
                  onChange={(e) => setNama(e.target.value)}
                />
              </div>
              <button
                type="submit"
                className="btn btn-primary"
                disabled={isLoading}
              >
                {isLoading ? (
                  "Menyimpan..."
                ) : (
                  <>
                    <BiSave /> Simpan
                  </>
                )}
              </button>
            </form>
          </Col>
        </Row>
      </div>
    </>
  );
}

export default TambahJenis;
